version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: bassin_web_1
      APP_PORT: 80
    container_name: bassin_app_proxy_1

  init:
    image: alpine
    entrypoint: /bin/sh -c 'apk add envsubst && cat /conf/ckpool.conf.template | envsubst > /conf/ckpool.conf && chown 1000:1000 /conf/ckpool.conf'
    volumes:
      - ${APP_DATA_DIR}/conf:/conf
    environment:
      - APP_BITCOIN_NODE_IP=${APP_BITCOIN_NODE_IP}
      - APP_BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}
      - APP_BITCOIN_RPC_PASS=${APP_BITCOIN_RPC_PASS}
      - APP_BITCOIN_RPC_PORT=${APP_BITCOIN_RPC_PORT}
      - APP_BITCOIN_ZMQ_SEQUENCE_PORT=${APP_BITCOIN_ZMQ_SEQUENCE_PORT}

  ckpool:
    image: pinkyswear/ckpool-solo
    entrypoint: /bin/sh -c 'while [ ! -f /srv/ckpool/conf/ckpool.conf ]; do echo "Waiting for ckpool.conf to be ready..."; sleep 1; done; rm -f /tmp/ckpool/main.pid && ./bin/ckpool -B -c ./conf/ckpool.conf'
    depends_on:
      - init
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "3456:3333/tcp"
    volumes:
      - ${APP_DATA_DIR}/conf:/srv/ckpool/conf
      - ${APP_DATA_DIR}/web:/srv/ckpool/web
    container_name: bassin_ckpool_1

  web:
    image: halverneus/static-file-server
    environment:
      - FOLDER=/web
      - PORT=80
    volumes:
      - ${APP_DATA_DIR}/web:/web
    restart: on-failure
    container_name: bassin_web_1