version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: bassin_web_1
      APP_PORT: 80
  
  init:
    image: alpine
    entrypoint: /bin/sh -c 'apk add envsubst && cat /conf/ckpool.conf.template | envsubst > /conf/ckpool.conf && chown 1000:1000 /conf/ckpool.conf'
    volumes:
      - ${APP_DATA_DIR}/conf:/conf
    environment:
      - APP_BITCOIN_NODE_IP=${APP_BITCOIN_NODE_IP}
      - APP_BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}
      - APP_BITCOIN_RPC_PASS=${APP_BITCOIN_RPC_PASS}

  ckpool:
    image: pinkyswear/ckpool-solo
    entrypoint: /bin/sh -c 'while [ ! -f /conf/ckpool.conf ]; do echo "Waiting for ckpool.conf to be ready..."; sleep 1; done; rm -f /tmp/ckpool/main.pid && ./bin/ckpool -B -c ./conf/ckpool.conf'
    depends_on:
      - init
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "5333:3333/tcp"
    volumes:
      - ${APP_DATA_DIR}/conf:/conf
      - ${APP_DATA_DIR}/logs:/logs
  
  web:
    image: halverneus/static-file-server
    environment:
      - FOLDER=/web
      - PORT=80
    volumes:
      - ${APP_DATA_DIR}/logs:/web
    restart: on-failure